apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: gitea
    server: "https://kubernetes.default.svc"
  source:
    path: software/cluster/gitea/helmchart
    repoURL: "https://github.com/Groupeffect/monotremata.git"
    targetRevision: dev/local
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - Replace=true
